name: Change Request
description: Please describe the details of the problem that is adressed by this change request!
title: "Please specify the name of your change request"
labels: ["change request", "triage"]
body:
  - type: dropdown
    id: browsers
    attributes:
      label: Do you raise this change request because the ILCD+EPD format...
      options:
        - lacks compliance with regualtions.
        - lacks conformaty with standards.
        - has another problem or use case I´m trying to address.
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Please include links, documents or further information in English if applicable.
      placeholder: Please describe the regulation or standard you try to comply with or problem you are trying to solve with this change request.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the proferred solution from your point of view.
      description: Please describe the problem you are trying to solve in detail.
      placeholder: Please include links to documents and further information if applicable.
    validations:
      required: true
