name: Change Request
description: Please describe the details of the problem that is adressed by this change request!
title: "Please specify the name of your change request"
labels: ["change request", "triage"]
body:
  - type: checkboxes
    id: reason
    attributes:
      label: I raise this change request because...
      options:
        - label: the ILCD+EPD format lacks compliance with regualtions.
        - label: the ILCD+EPD format lacks conformaty with standards.
        - label: the ILCD+EPD format needs to be improved regarding existing format or master data elements.
        - label: there is another problem or use case I´m trying to address.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Please include links, documents or further information in English if applicable.
      placeholder: Please describe the regulation or standard you try to comply with or problem you are trying to solve with this change request.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution description
      description: Please include links, documents or further information in English if applicable.
      placeholder: Please describe the preferred solution from your point of view.
    validations:
      required: true
  - type: textarea
    id: relevance
    attributes:
      label: Relevance or added value
      description: Please include links, documents or further information in English if applicable.
      placeholder: Please describe the relevance or added value of your solution.
