name: Change Request
description: Please describe the details of the problem that is adressed by this change request!
title: "Please specify the name of your change request "
labels: ["change request", "triage"]
body:
  - type: dropdown
    id: browsers
    attributes:
      label: Why do you raise this change request? Please select the most applicable option!
      multiple: true
      options:
        - Compliance with regualtions
        - Conformaty with standards
        - Other use case
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Please include links, documents or further information if applicable.
      placeholder: Please describe the problem you are trying to solve with this change request in detail.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like.
      description: Please describe the problem you are trying to solve in detail.
      placeholder: Please include links to documents and further information if applicable.
    validations:
      required: true
