name: Change Request
description: Please describe the details of the problem that is adressed by this change request!
title: "Please specify the name of your change request"
labels: ["change request", "triage"]
body:
- type: markdown
    value: "Welcome!"
- type: markdown
    value: Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
  - type: checkboxes
    id: reason
    attributes:
      label: I raise this change request because...
      options:
        - label: the ILCD+EPD format lacks compliance with regualtions.
        - label: the ILCD+EPD format lacks conformaty with standards.
        - label: the ILCD+EPD format needs to be improved regarding existing format or master data elements.
        - label: there is another problem or use case I´m trying to address.
  - type: textarea
    id: problem
    attributes:
      label: Problem description
      description: Please include links, documents or further information in English if applicable.
      placeholder: Please describe the regulation or standard you try to comply with or problem you are trying to solve with this change request.
  - type: textarea
    id: solution
    attributes:
      label: Describe the proferred solution from your point of view.
      description: Please describe the problem you are trying to solve in detail.
      placeholder: Please include links to documents and further information if applicable.
  - type: textarea
    id: relevance
    attributes:
      label: Describe the relevance or added value of your solution.
      description: Please describe the relevance or added value of your solution.
      placeholder: Please include links to documents and further information if applicable.
