name: deploy html documentation

on:
  push:
    paths:
      - 'doc/schemadoc/**' 
    branches:
      - '**'  
    branches-ignore:
      - 'main'
      
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the current branch where the changes were made
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      # Step 2: Checkout the gitActions branch
      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions
          path: gitActions

      # Step 3: Copy HTML files from the current branch to gitActions/gitBranches/{branch_name}
      - name: Copy HTML files to gitActions branch
        run: |
          branch_name=${{ github.ref_name }}
          echo "Updating HTML files from $branch_name to gitBranches/$branch_name in gitActions branch."

          # Ensure the directory exists in gitActions
          mkdir -p gitActions/gitBranches/$branch_name

          # Copy the HTML files from the current branch to the gitActions branch folder
          cp -r ./doc/schemadoc/* gitActions/gitBranches/$branch_name/

      # Step 4: Commit and push changes to gitActions branch
      - name: Commit and push changes to gitActions branch
        working-directory: gitActions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gitBranches/$branch_name
          git commit -m "Updated HTML files for $branch_name"
          git push origin gitActions
