name: Sync Main Branch to GitActions

on:
  push:
    branches:
      - mainTest

permissions:
  contents: write

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions
          fetch-depth: 0 
      - name: Fetch mainTest branch
        run: git fetch origin mainTest

      - name: Replace content of gitActions/mainBranch with mainTest content
        run: |
          git checkout origin/mainTest -- .  
          rm -rf gitActions/mainBranch/*  
          mkdir -p gitActions/mainBranch
          cp -r * gitActions/mainBranch/  
          git add gitActions/mainBranch
          git commit -m "Sync mainTest to gitActions/mainBranch" || echo "No changes to commit"
          git push origin gitActions
