name: Create ILCD-EPD-Data-Format ZIP

on:
  # push:
  #   branches:
  #     - gitActions
  pull_request:
    branches:
      - gitActions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create ZIP archive
      run: zip -r ILCD-EPD-Data-Format-$(date +%Y-%m-%d_%H-%M).zip .

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v4
      with:
        name: ILCD-EPD-Data-Format-zip
        path: ILCD-EPD-Data-Format-*.zip
