name: Convert CSV to HTML

on:
  push:
    branches:
      - main
      - gitActions

permissions:
  contents: write  # Set permissions for the entire workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Convert CSV to HTML
      run: |
        python - <<EOF
        import pandas as pd
        import glob
        import os

        # Create the output directory if it doesn't exist
        output_dir = "doc/html_output"
        os.makedirs(output_dir, exist_ok=True)

        # Get all CSV files in the /doc/ directory
        csv_files = glob.glob("doc/*.csv")
        if not csv_files:
            print("No CSV files found to process.")
        else:
            for csv_file in csv_files:
                print(f"Processing {csv_file}...")
                # Read the CSV file
                df = pd.read_csv(csv_file)
                
                # Convert the DataFrame to an HTML table
                html_table = df.to_html(index=False, classes='table table-striped', border=0)
                
                # Save the HTML table to a file
                html_filename = os.path.join(output_dir, os.path.basename(csv_file).replace('.csv', '.html'))
                with open(html_filename, 'w') as f:
                    f.write(f"""
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
                        <script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.17.0/xlsx.full.min.js"></script>
                        <title>{os.path.basename(csv_file)}</title>
                    </head>
                    <body>
                        <div class="container">
                            <h1>{os.path.basename(csv_file)}</h1>
                            <button id='download-button' class='btn btn-primary'>Download as Excel</button>
                            {html_table}
                        </div>
                        <script>
                            document.getElementById('download-button').addEventListener('click', function () {
                                var wb = XLSX.utils.table_to_book(document.querySelector('.table'), {sheet: 'Sheet JS'});
                                XLSX.writeFile(wb, '{os.path.basename(csv_file).replace('.csv', '.xlsx')}');
                            });
                        </script>
                    </body>
                    </html>
                    """)
            print(f"HTML files generated: {os.listdir(output_dir)}")
        EOF

    - name: Check HTML output
      run: |
        echo "Listing files in doc/html_output directory"
        ls -l doc/html_output || echo "doc/html_output directory not found or is empty"

    - name: Commit and push HTML files
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add doc/html_output/*.html || exit 0
        git commit -m 'Automated conversion of CSV to HTML'
        git push origin HEAD:gitActions
