name: Convert CSV to HTML

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Convert CSV to HTML
      run: |
        python - <<EOF
        import pandas as pd
        import glob
        import os

        # Create the output directory if it doesn't exist
        output_dir = "htmlData"
        os.makedirs(output_dir, exist_ok=True)

        # Get all CSV files in the current directory
        csv_files = glob.glob("*.csv")

        for csv_file in csv_files:
            # Read the CSV file
            df = pd.read_csv(csv_file)
            
            # Convert the DataFrame to an HTML table
            html_table = df.to_html(index=False, classes='table table-striped', border=0)
            
            # Save the HTML table to a file
            html_filename = os.path.join(output_dir, csv_file.replace('.csv', '.html'))
            with open(html_filename, 'w') as f:
                f.write(f"""
                <!DOCTYPE html>
                <html>
                <head>
                    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
                    <title>{csv_file}</title>
                </head>
                <body>
                    <div class="container">
                        <h1>{csv_file}</h1>
                        {html_table}
                    </div>
                </body>
                </html>
                """)
        EOF

    - name: Commit and push HTML files
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add html_output/*.html
        git commit -m 'Automated conversion of CSV to HTML'
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
