name: Convert CSV to HTML and Deploy to GitHub Pages

on:
  push:
    branches:
      - gitActions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Convert CSV to HTML
      run: |
        python - <<EOF
        import pandas as pd
        import glob
        import os

        # Create the output directory if it doesn't exist
        output_dir = "html_output"
        os.makedirs(output_dir, exist_ok=True)

        # Get all CSV files in the /doc/ directory
        csv_files = glob.glob("doc/*.csv")
        if not csv_files:
            print("No CSV files found to process.")
        else:
            for csv_file in csv_files:
                print(f"Processing {csv_file}...")
                # Read the CSV file
                df = pd.read_csv(csv_file)
                
                # Convert the DataFrame to an HTML table
                html_table = df.to_html(index=False, classes='table table-striped', border=0)
                
                # Save the HTML table to a file
                html_filename = os.path.join(output_dir, os.path.basename(csv_file).replace('.csv', '.html'))
                with open(html_filename, 'w') as f:
                    f.write(f"""
                    <!DOCTYPE html>
                    <html>
                    <head>
                        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
                        <title>{os.path.basename(csv_file)}</title>
                    </head>
                    <body>
                        <div class="container">
                            <h1>{os.path.basename(csv_file)}</h1>
                            {html_table}
                        </div>
                    </body>
                    </html>
                    """)
            print(f"HTML files generated: {os.listdir(output_dir)}")
        EOF

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html_output
