name: Deploy HTML Documentation for New Branch

on:
  create:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the newly created branch
      - name: Checkout newly created branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      # Step 2: Checkout the gitActions branch
      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions
          path: gitActions

      # Step 3: Copy HTML files from the new branch to gitActions/gitBranches
      - name: Copy HTML files to gitActions branch
        run: |
          new_branch=${{ github.ref_name }}
          echo "Copying HTML files from $new_branch to gitBranches/$new_branch in gitActions branch."

          # Ensure the directory exists in gitActions
          mkdir -p gitActions/gitBranches/$new_branch

          # Copy the HTML files from the current branch to the gitActions branch folder
          cp -r ./doc/schemadoc/* gitActions/gitBranches/$new_branch/

      # Step 4: Commit and push changes to gitActions branch
      - name: Commit and push changes to gitActions branch
        working-directory: gitActions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gitBranches
          git commit -m "Added HTML files for ${{ github.ref_name }}"
          git push origin gitActions

      # Step 5: Update README.md in the new branch with links to HTML files
      - name: Update README.md in new branch
        run: |
          new_branch=${{ github.ref_name }}
          readme_path="README.md"
          
          # Create links for the new branch
          links="
          # ILCD-EPD-Data-Format\n\n
          - [EPD DataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/EPD_DataSet.html)\n
          - [EPD FlowDataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/EPD_FlowDataSet.html)\n
          - [ILCD Common DataTypes](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_Common_DataTypes.html)\n
          - [ILCD Common EnumerationValues](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_Common_EnumerationValues.html)\n
          - [ILCD ContactDataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_ContactDataSet.html)\n
          - [ILCD FlowPropertyDataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_FlowPropertyDataSet.html)\n
          - [ILCD LCIAMethodDataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_LCIAMethodDataSet.html)\n
          - [ILCD SourceDataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_SourceDataSet.html)\n
          - [ILCD UnitGroupDataSet](https://indatawg.github.io/ILCD-EPD-Data-Format/gitBranches/$new_branch/ILCD_UnitGroupDataSet.html)\n
          "

          # Add links to README.md
          echo -e "$links" >> $readme_path

      # Step 6: Commit and push the updated README.md to the new branch
      - name: Commit and push updated README.md
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README.md with links to rendered HTML files"
          git push origin ${{ github.ref_name }}
