name: Deploy HTML-Documentation

on:
  push:
    branches:
      - feature/test_branch
  
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the gitActions branch to work in it
      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions

      # Step 2: Fetch all branches from the repository
      - name: Fetch all branches
        run: git fetch --all

      # Step 3: Iterate through each branch, except gitActions, and create the subdirectory
      - name: Create subdirectories for all branches except gitActions
        run: |
          for branch in $(git branch -r | grep -v "gitActions" | grep -v "HEAD" | sed 's/origin\///'); do
            echo "Processing branch: $branch"
            
            # Check if the directory for this branch already exists
            if [ -d "gitBranches/$branch" ]; then
              echo "Subfolder for $branch already exists. Skipping."
            else
              echo "Creating subfolder for $branch."
              
              # Checkout the branch
              git checkout $branch
              
              # Copy HTML files to the corresponding subdirectory
              mkdir -p gitBranches/$branch
              cp -r ./doc/schemadoc/* gitBranches/$branch/
            fi
          done

      # Step 4: Commit and push changes to gitActions branch
      - name: Commit and push changes
        run: |
          git checkout gitActions
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gitBranches
          git commit -m "Added HTML files for all branches"
          git push origin gitActions
