name: Sync Main Branch to GitActions

on:
  push:
    branches:
      - mainTest

permissions:
  contents: write

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sync Main Branch to gitActions/mainBranch
        run: |
          git fetch origin gitActions
          git checkout gitActions
          rm -rf mainBranch  # Remove existing mainBranch content
          mkdir -p mainBranch
          git checkout mainTest -- .  # Copy all files from mainTest to current directory
          mv * mainBranch/  # Move them into mainBranch directory
          git add mainBranch
          git commit -m "Sync main branch to gitActions" || echo "No changes to commit"
          git push origin gitActions
