name: Sync Main Branch to GitActions

on:
  push:
    branches:
      - mainTest

permissions:
  contents: write

jobs:
  sync-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions

      - name: Replace content of gitActions/mainBranch with mainTest content
        run: |
          git checkout mainTest -- .  # Check out the latest content from mainTest
          rm -rf gitActions/mainBranch/*  # Remove everything in the mainBranch folder
          mkdir -p gitActions/mainBranch
          cp -r * gitActions/mainBranch/  # Copy the new content into mainBranch
          git add gitActions/mainBranch
          git commit -m "Sync mainTest to gitActions/mainBranch" || echo "No changes to commit"
          git push origin gitActions
