name: Sync Main Branch to GitActions

on:
  push:
    branches:
      - 'mainTest'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mainTest branch
        uses: actions/checkout@v2
        with:
          ref: mainTest

      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions
          path: gitActions

      - name: Clean mainBranch directory in gitActions
        run: rm -rf gitActions/mainBranch

      - name: Copy content to mainBranch folder in gitActions branch
        run: |
          echo "Updating content from mainTest branch to gitActions/mainBranch."
          mkdir -p gitActions/mainBranch
          rsync -avL --exclude='gitActions' ./ gitActions/mainBranch/

      - name: Verify copied files
        run: ls -la gitActions/mainBranch

      - name: Commit and push changes to gitActions branch
        working-directory: gitActions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gitActions
          git add mainBranch
          git commit -m "Updated content for mainBranch"
          git push origin gitActions --force
