name: Sync Main Branch to GitActions

on:
  push:
    branches:
      - 'mainTest'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mainTest branch
        uses: actions/checkout@v2
        with:
          ref: mainTest

      - name: Checkout gitActions branch
        uses: actions/checkout@v2
        with:
          ref: gitActions
          path: gitActions

      - name: Copy content to gitBranches folder in gitActions branch
        run: |
          echo "Updating content from mainTest branch to gitActions/gitBranches."
          mkdir -p gitActions/gitBranches
          rsync -av ./ gitActions/gitBranches/

      - name: Verify copied files
        run: ls -la gitActions/gitBranches

      - name: Commit and push changes to gitActions branch
        working-directory: gitActions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout gitActions
          git add gitBranches
          git commit -m "Updated content for gitBranches"
          git push origin gitActions --force
