name: Create Version and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create release zip and copy doc folder
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        DOC_DIR="doc/releases/${TAG_NAME}"
        mkdir -p ${DOC_DIR}
        ZIP_FILE="${DOC_DIR}/${TAG_NAME}.zip"
        # Create the zip file, excluding the releases directory
        zip -r $ZIP_FILE . -x "doc/releases/*"
        echo "Created zip file: $ZIP_FILE"
        # Copy the contents of the doc folder to the DOC_DIR
        rsync -av --exclude=${DOC_DIR} doc/ ${DOC_DIR}/doc/
        echo "Copied doc folder to: ${DOC_DIR}"
      shell: bash

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      shell: bash

    - name: Checkout gitActions branch
      run: |
        git fetch origin gitActions
        git checkout gitActions
      shell: bash

    - name: Copy files to gitActions branch
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        DOC_DIR="doc/releases/${TAG_NAME}"
        # Preserve folder structure and copy to the correct location
        cp -r ${DOC_DIR} doc/releases/
        git add .
        git commit -m "Add versioned documentation and zip for ${TAG_NAME}"
        git push origin gitActions
      shell: bash

    - name: Update Previous Versions in README
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        echo "- [${TAG_NAME}](doc/releases/${TAG_NAME}/index.html)" >> README.md
        git add README.md
        git commit -m "Add ${TAG_NAME} to Previous versions in README"
        git push origin gitActions
      shell: bash
