name: Create Version and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0

permissions:
  contents: write  # Grants write permissions to the contents of the repository

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create release zip
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        ZIP_FILE="doc/releases/${TAG_NAME}.zip"
        mkdir -p doc/releases
        zip -r $ZIP_FILE .
        echo "Created zip file: $ZIP_FILE"

    - name: Configure Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Create Versioned Documentation Page
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        DOC_DIR="doc/releases/${TAG_NAME}"
        mkdir -p ${DOC_DIR}
        cat <<EOF > ${DOC_DIR}/index.html
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>${TAG_NAME} Documentation</title>
        </head>
        <body>
            <h1>ILCD-EPD-Data-Format</h1>

            <h2>Schema Documentation</h2>
            <ul>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/EPD_DataSet.html">EPD_DataSet</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/EPD_FlowDataSet.html">EPD_FlowDataSet</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_Common_DataTypes.html">ILCD_Common_DataTypes</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_Common_EnumerationValues.html">ILCD_Common_EnumerationValues</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_ContactDataSet.html">ILCD_ContactDataSet</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_FlowPropertyDataSet.html">ILCD_FlowPropertyDataSet</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_LCIAMethodDataSet.html">ILCD_LCIAMethodDataSet</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_SourceDataSet.html">ILCD_SourceDataSet</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/schemadoc/ILCD_UnitGroupDataSet.html">ILCD_UnitGroupDataSet</a></li>
            </ul>

            <h2>Background Database</h2>
            <ul>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/BackgroundDB_SourceDatasets_ecoinvent.html">BackgroundDB_SourceDatasets_ecoinvent</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/BackgroundDB_SourceDatasets_GaBi.html">BackgroundDB_SourceDatasets_GaBi</a></li>
            </ul>
          
            <h2>Indicators</h2>
            <ul>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/EN15804+A1_indicators.html">EN15804+A1 indicators</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/EN15804+A2_indicators.html">EN15804+A2 indicators</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/Common_references.html">Common references</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/Country_specific_indicators.html">Country specific indicators</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/data/html_output/Flow_properties_and_unit_groups.html">Flow properties and unit groups</a></li>
            </ul>

            <h2>Download Excel Files</h2>
            <ul>
                <li><a href="../../releases/${TAG_NAME}/doc/data/excel_output/BackgroundData.xlsx">Download Background Database</a></li>
                <li><a href="../../releases/${TAG_NAME}/doc/data/excel_output/Indicators.xlsx">Download Indicators</a></li>
            </ul>
        </body>
        </html>
        EOF

    - name: Commit and push documentation
      if: success()
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add doc/releases/${TAG_NAME}/index.html
        git commit -m "Add versioned documentation for ${TAG_NAME}"
        git push origin HEAD

    - name: Update Previous Versions in README
      if: success()
      run: |
        TAG_NAME=${GITHUB_REF##*/}
        echo "- [${TAG_NAME}](https://indatawg.github.io/ILCD-EPD-Data-Format/doc/releases/${TAG_NAME}/index.html)" >> README.md
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Add ${TAG_NAME} to Previous versions in README"
        git push origin HEAD
